- migrations/20230807020810_add_time_index_block_tx.ts
> feat: add migration to add index time to block, tx (develop)

- migrations/20230807020810_add_time_index_block_tx.ts
> feat: add migration to add index time to block, tx (staging)

- src/services/crawl-tx/crawl_tx.service.ts
> fix: add order when query block (develop)

- src/services/crawl-tx/crawl_tx.service.ts
> fix: add order when query block (staging)

- src/services/api-gateways/graphiql.service.ts
> fix: allow whitelist query can have depth more than config (develop)

- src/services/api-gateways/graphiql.service.ts
> fix: allow whitelist query can have depth more than config (staging)

- migrations/20230809073622_index_cw20_models.ts
- src/models/cw20_activity.ts
- src/models/cw721_tx.ts
> Refactor/cw20 index and relation ( staging )

- ci/config.json.ci
- config.json
- src/common/constant.ts
- src/models/cw20_activity.ts
- src/models/cw20_contract.ts
- src/models/cw20_holder.ts
- src/models/cw20_total_holder_stats.ts
- src/services/api-gateways/api_gateway.service.ts
- src/services/api-gateways/cw20_admin.service.ts
- src/services/cw20/cw20.service.ts
- src/services/cw20/cw20_reindexing.service.ts
- src/services/cw20/cw20_update_by_contract.service.ts
- test/unit/services/cw20/cw20.spec.ts
- test/unit/services/cw20/cw20_reindexing.spec.ts
> Feat/reindex cw20 ( staging )

- migrations/20230817015916_modify_column_table_account_statistic.ts
- src/services/statistics/account_statistics.service.ts
> fix: update column in account_statistic table, update bignum top_tx_sent (develop)

- ci/config.json.ci
- config.json
- migrations/20230810094108_create_ibc_tx_model.ts
- src/common/constant.ts
- src/models/event.ts
- src/models/event_attribute.ts
- src/models/ibc_message.ts
- src/models/index.ts
- src/services/ibc/crawl_ibc_app.service.ts
- test/unit/services/ibc/crawl_ibc_app.spec.ts
> Feat/ibc app ( develop )

- migrations/20230817015916_modify_column_table_account_statistic.ts
- src/services/statistics/account_statistics.service.ts
> fix: update column in account_statistic table, update bignum top_tx_sent (staging)

- src/services/statistics/account_statistics.service.ts
> Fix/account stat with feegrant (staging)

- migrations/20230912095510_smart_contract_add_label.ts
- src/models/event_attribute.ts
- src/models/smart_contract.ts
- src/services/crawl-cosmwasm/crawl_smart_contract.service.ts
- test/unit/services/crawl-cosmwasm/crawl_smart_contract.spec.ts
> fix: smart contract missing label ( develop )

- ci/config.json.ci
- config.json
- src/common/constant.ts
- src/models/event_attribute.ts
- src/services/api-gateways/api_gateway.service.ts
- src/services/api-gateways/services-manager.service.ts
- src/services/manager/services-manager.service.ts
> feat: health check job ( develop )

- src/services/cw721/cw721-media.service.ts
> refactor: performance cw721 media info ( develop)

- ci/config.json.ci
- config.json
- src/common/constant.ts
- src/services/api-gateways/api_gateway.service.ts
- src/services/api-gateways/job.service.ts
- src/services/job/create_event_attr_partition.service.ts
- src/services/job/create_index_composite_in_attr_partition.service.ts
> Feat/create composite index in partition attribute (develop)

- package-lock.json
- package.json
- src/services/crawl-block/crawl_block.service.ts
- src/services/crawl-tx/aura.registry.ts
- src/services/crawl-tx/crawl_tx.service.ts
- src/services/job/reassign_msg_index_to_event.service.ts
- test/unit/services/crawl-block/parse_block_event.spec.ts
- test/unit/services/job/reassign_msg_index_to_event.spec.ts
> Feat/upgrade cosmos sdk 0.47.4 merge develop

- migrations/20231002080503_ibc_message_add_tx_hash.ts
- src/models/ibc_message.ts
- src/services/ibc/crawl_ibc_app.service.ts
- test/unit/services/ibc/crawl_ibc_app.spec.ts
> Refactor/ibc message add tx hash ( develop )

- .github/workflows/test.yml
- docker-compose.yml
- package.json
- src/services/crawl-block/crawl_block.service.ts
- src/services/crawl-tx/aura.registry.ts
- src/services/crawl-tx/crawl_tx.service.ts
- src/services/job/reassign_msg_index_to_event.service.ts
- test/unit/services/crawl-block/parse_block_event.spec.ts
- test/unit/services/crawl-proposal/crawl_tally_proposal.spec.ts
- test/unit/services/crawl-transaction/parse_transaction.spec.ts
- test/unit/services/crawl-validator/crawl_validator.spec.ts
- test/unit/services/job/reassign_msg_index_to_event.spec.ts
> Feat/upgrade cosmos sdk 0.47.4 merge staging

- hasura/metadata/databases/auratestnet/tables/public_ibc_ics20.yaml
- hasura/metadata/databases/euphoria/tables/public_ibc_ics20.yaml
- hasura/metadata/databases/nois/tables/public_ibc_ics20.yaml
- hasura/metadata/databases/serenity/tables/public_ibc_ics20.yaml
- hasura/metadata/databases/theta/tables/public_ibc_ics20.yaml
- hasura/metadata/databases/xstaxy/tables/public_ibc_ics20.yaml
> feat: allow ibc ics20 aggregate

- src/services/api-gateways/api_gateway.service.ts
- src/services/api-gateways/services-manager.service.ts
> refactor: change version api healtcheck

- ci/config.json.ci
- config.json
- src/services/crawl-validator/crawl_signing_info.service.ts
- src/services/crawl-validator/crawl_validator.service.ts
> fix: deadlock validator (develop)

- hasura/metadata/databases/auratestnet/tables/public_cw20_activity.yaml
- hasura/metadata/databases/euphoria/tables/public_cw20_activity.yaml
- hasura/metadata/databases/nois/tables/public_cw20_activity.yaml
- hasura/metadata/databases/serenity/tables/public_cw20_activity.yaml
- hasura/metadata/databases/xstaxy/tables/public_cw20_activity.yaml
- migrations/20231009074209_cw20_activity_add_tx_hash.ts
- src/models/cw20_activity.ts
- src/models/cw20_contract.ts
- src/services/cw20/cw20.service.ts
- src/services/cw20/cw20_reindexing.service.ts
- src/services/cw20/cw20_update_by_contract.service.ts
- test/unit/services/cw20/cw20.spec.ts
- test/unit/services/cw20/cw20_update_by_contract.spec.ts
> refactor: cw20 activity add tx hash ( develop )

- src/services/crawl-validator/crawl_validator.service.ts
> fix: move get validators info outside knex.transaction (develop)

- ci/.env.ci
- migrations/20231018075539_update_offchain_image_animation_url.ts
- src/services/cw721/cw721-media.service.ts
- test/unit/services/cw721/cw721-media.spec.ts
> fix: hotfix cw721 media offchain url ( develop )

- ci/config.json.ci
- config.json
- src/common/constant.ts
- src/services/crawl-tx/crawl_tx.service.ts
- src/services/job/update_sender_in_tx_message.service.ts
- src/services/job/update_sender_in_tx_message.ts
> fix: update sender in transaction_message (staging)

- ci/config.json.ci
- config.json
- src/services/crawl-validator/crawl_signing_info.service.ts
- src/services/crawl-validator/crawl_validator.service.ts
> fix: deadlock validator (staging)

- src/common/constant.ts
- src/models/proposal.ts
- src/services/api-gateways/api_gateway.service.ts
- src/services/api-gateways/job.service.ts
- src/services/crawl-tx/aura.registry.ts
- src/services/job/redecode_tx.service.ts
> Feat/decode submit proposal cosmos 0.47 (develop)

- src/common/constant.ts
- src/models/proposal.ts
- src/services/api-gateways/api_gateway.service.ts
- src/services/api-gateways/job.service.ts
- src/services/crawl-tx/aura.registry.ts
- src/services/job/redecode_tx.service.ts
> Feat/decode submit proposal cosmos 0.47 (staging)

- src/services/cw721/cw721_handler.ts
> Fix/cw721 reindex history ( develop )

- src/services/cw721/cw721-reindexing.service.ts
- src/services/cw721/cw721_handler.ts
> Fix/cw721 reindex history ( develop ): empty owner

- migrations/20231009074209_cw20_activity_add_tx_hash.ts
- src/models/cw20_activity.ts
- src/models/cw20_contract.ts
- src/models/cw721_tx.ts
- src/services/cw20/cw20.service.ts
- src/services/cw20/cw20_reindexing.service.ts
- src/services/cw20/cw20_update_by_contract.service.ts
- test/unit/services/cw20/cw20.spec.ts
- test/unit/services/cw20/cw20_update_by_contract.spec.ts
> Refactor/cw20 activity add tx hash ( staging )

- src/models/cw721_tx.ts
- src/services/cw721/cw721-reindexing.service.ts
- src/services/cw721/cw721.service.ts
- src/services/cw721/cw721_handler.ts
> Fix/cw721 reindex history ( staging )

- src/common/utils/utils.ts
- src/models/proposal.ts
- src/services/crawl-proposal/crawl_proposal.service.ts
- src/services/crawl-proposal/crawl_tally_proposal.service.ts
> feat: use gov.v1 instead gov.v1beta1 when crawl proposal info (develop)

- src/services/cw721/cw721.service.ts
Not count action approve, revoke on cw721 activity
> chore: not count approve and revoke in cw721 activity

- src/services/cw721/cw721.service.ts
> chore: not count approve and revoke in cw721 activity (staging)

- ci/config.json.ci
- config.json
- src/services/crawl-tx/crawl_tx.service.ts
> fix: add pagination when crawl tx in block (develop)

- src/services/cw721/cw721.service.ts
> chore: not count approve and revoke in cw721 activity (main)

- ci/config.json.ci
- config.json
- src/services/crawl-tx/crawl_tx.service.ts
> fix: add pagination when crawl tx in block (staging)

- src/common/utils/utils.ts
- src/models/proposal.ts
- src/services/crawl-proposal/crawl_proposal.service.ts
- src/services/crawl-proposal/crawl_tally_proposal.service.ts
> feat: use gov.v1 instead gov.v1beta1 when crawl proposal info (staging)

- config.json
- src/common/constant.ts
- src/services/job/create_constraint_in_attr_partition.service.ts
> Feat/job create constraint partition event attribute (develop)

- src/services/crawl-proposal/crawl_proposal.service.ts
> Fix/skip if not found proposal onchain (develop)

- src/services/cw721/cw721-reindexing.service.ts
> fix: reindex migrate contract

- config.json
- hasura/metadata/databases/auratestnet/tables/m_view_ibc_relayer_statistic.yaml
- hasura/metadata/databases/auratestnet/tables/view_ibc_channel_detail_statistic.yaml
- hasura/metadata/databases/euphoria/tables/m_view_ibc_relayer_statistic.yaml
- hasura/metadata/databases/euphoria/tables/view_ibc_channel_detail_statistic.yaml
- hasura/metadata/databases/nois/tables/m_view_ibc_relayer_statistic.yaml
- hasura/metadata/databases/nois/tables/view_ibc_channel_detail_statistic.yaml
- hasura/metadata/databases/sei/tables/m_view_ibc_relayer_statistic.yaml
- hasura/metadata/databases/sei/tables/view_ibc_channel_detail_statistic.yaml
- hasura/metadata/databases/serenity/tables/m_view_ibc_relayer_statistic.yaml
- hasura/metadata/databases/serenity/tables/view_ibc_channel_detail_statistic.yaml
- hasura/metadata/databases/xstaxy/tables/m_view_ibc_relayer_statistic.yaml
- hasura/metadata/databases/xstaxy/tables/view_ibc_channel_detail_statistic.yaml
- migrations/20231122062744_create_m_view_ibc_relayer_statistic.ts
- migrations/20231123024441_create_view_ibc_channel_detail_statistic.ts
- src/common/constant.ts
- src/services/ibc/ibc_statistic.servicce.ts
> chore: ibc relayer statistic

- src/services/crawl-proposal/crawl_proposal.service.ts
> fix: skip proposal if not found onchain (staging)

- src/services/job/create_constraint_in_attr_partition.service.ts
Reverts aura-nw/horoscope-v2#519
> Revert "fix: update query drop constraint in attr partition"

- src/services/crawl-validator/crawl_delegators.service.ts
- test/unit/services/crawl-validator/crawl_delegators.spec.ts
refer #477 (develop)
refer #532 (main)
> Fix/improve crawl delegator (staging)

- migrations/20231208095427_add-index-tx-hash-to-cw20-activity.ts
> chore: add index tx_hash to cw20_activity (staging)

- migrations/20231020083123_remove_column_signature_in_block_signature.ts
- src/models/block_signature.ts
- src/services/crawl-block/crawl_block.service.ts
> feat: remove column signature in block_signature table (staging)

- migrations/20231208095427_add-index-tx-hash-to-cw20-activity.ts
> feat: add index tx_hash to cw20_activity 

- config.json
- hasura/metadata/databases/auratestnet/tables/m_view_ibc_relayer_statistic.yaml
- hasura/metadata/databases/auratestnet/tables/view_ibc_channel_detail_statistic.yaml
- hasura/metadata/databases/euphoria/tables/m_view_ibc_relayer_statistic.yaml
- hasura/metadata/databases/euphoria/tables/view_ibc_channel_detail_statistic.yaml
- hasura/metadata/databases/nois/tables/m_view_ibc_relayer_statistic.yaml
- hasura/metadata/databases/nois/tables/view_ibc_channel_detail_statistic.yaml
- hasura/metadata/databases/sei/tables/m_view_ibc_relayer_statistic.yaml
- hasura/metadata/databases/sei/tables/view_ibc_channel_detail_statistic.yaml
- hasura/metadata/databases/serenity/tables/m_view_ibc_relayer_statistic.yaml
- hasura/metadata/databases/serenity/tables/view_ibc_channel_detail_statistic.yaml
- hasura/metadata/databases/xstaxy/tables/m_view_ibc_relayer_statistic.yaml
- hasura/metadata/databases/xstaxy/tables/view_ibc_channel_detail_statistic.yaml
- migrations/20231122062744_create_m_view_ibc_relayer_statistic.ts
- migrations/20231123024441_create_view_ibc_channel_detail_statistic.ts
- src/common/constant.ts
- src/services/ibc/ibc_statistic.service.ts
> feat: Ibc statistic main

- ci/config.json.ci
- config.json
- src/services/crawl-tx/crawl_tx.service.ts
Reverts aura-nw/horoscope-v2#588
> Revert "fix: update tx_msg in job crawl_tx"

- hasura/metadata/databases/auratestnet/tables/account_balance.yaml
- hasura/metadata/databases/auratestnet/tables/tables.yaml
- hasura/metadata/databases/euphoria/tables/account_balance.yaml
- hasura/metadata/databases/euphoria/tables/tables.yaml
- hasura/metadata/databases/nois/tables/account_balance.yaml
- hasura/metadata/databases/nois/tables/tables.yaml
- hasura/metadata/databases/sei/tables/account_balance.yaml
- hasura/metadata/databases/sei/tables/tables.yaml
- hasura/metadata/databases/serenity/tables/account_balance.yaml
- hasura/metadata/databases/serenity/tables/tables.yaml
- hasura/metadata/databases/xstaxy/tables/account_balance.yaml
- hasura/metadata/databases/xstaxy/tables/tables.yaml
- migrations/20231226102519_add_balances_to_account.ts
- migrations/20231228022222_migrate-account-balances.ts
- src/models/account.ts
- src/models/account_balance.ts
- src/services/crawl-account/crawl_account.service.ts
> feat: add account balance table (#564)

- src/services/crawl-cosmwasm/crawl_smart_contract.service.ts
fullfill missing codeids before insert new/migrate contracts
> fix: handle missing code id

- ci/config.json.ci
- config.json
- src/common/utils/chain.registry.ts
- src/services/crawl-tx/crawl_tx.service.ts
- test/unit/services/crawl-transaction/coin_transfer.spec.ts
- test/unit/services/crawl-transaction/handle_authz_tx_msg.spec.ts
- test/unit/services/crawl-transaction/parse_transaction.spec.ts
- test/unit/services/cw20/cw20.spec.ts
- test/unit/services/handle-vote/handle_vote.spec.ts
> feat: use msg log instead of event log (evmos)

- ci/config.json.ci
- config.json
- migrations/20240227082932_create_evm_transaction_table.ts
- src/common/constant.ts
- src/common/utils/utils.ts
- src/models/evm_transaction.ts
- src/models/index.ts
- src/services/handle-tx-evm/handle_tx_evm.service.ts
- src/services/job/create_constraint_in_evm_transaction_partition.service.ts
- src/services/job/create_evm_transaction_partition.service.ts
- test/unit/services/job/create_constraint_evm_transaction_partition.spec.ts
- create evm_transaction model with partition
- job check need and create evm_transaction_partition
- job create constraint in evm_transaction_partition (constaint with tx_id and tx_msg_id)
> feat: create evm transaction model with partition

- ci/config.json.ci
- config.json
- src/services/crawl-block/crawl_block.service.ts
- src/services/crawl-tx/crawl_tx.service.ts
> fix: remove numberOfBlockPerCall to use blocksPerCall in crawl block, tx

- src/services/evm/erc20.service.ts
Try catch when query view function (name, symbol, totalSupply, decimals)
> fix: erc20 missing view function

- migrations/20240314065656_create_compile_detail_evm_contract_verification.ts
- src/models/evm_contract_verification.ts
- src/services/api-gateways/verify_contract_evm.service.ts
- src/services/evm/verify_contract_evm.service.ts
feat: validate input verify evm contract; add compile_detail to save result after compile contract
> feat: validate input verify evm contract

- migrations/20240321015030_create_composite_index_tx_id_sender_in_tx_msg.ts
cái này trước optimize bên aura rồi, em merge lại sang evmos
> feat: create composite index (sender, tx_id) in transaction_message

- migrations/evm/20240613070822_evm_internal_transaction_add_error_col.ts
- src/models/evm_internal_transaction.ts
- src/services/evm/evm_crawl_internal_tx.service.ts
> fix: crawl internal tx call error

- ci/config.json.ci
- config.json
- src/services/evm/erc20.service.ts
- src/services/evm/erc20_handler.ts
- test/unit/services/erc20/erc20_handler.spec.ts
- Add erc20 deposit and withdrawal activities
- Handle transfer when deposit or withdrawal
> feat: erc20 track deposit & withdrawal

- ci/config.json.ci
- config.json
- migrations/evm/20240702013020_add_col_to_save_cosmos_erc20.ts
- src/models/erc20_activity.ts
- src/models/event.ts
- src/models/event_attribute.ts
- src/services/evm/erc20.service.ts
- src/services/evm/erc20_handler.ts
```
if (config.evmOnly === false)
1. query cosmos event convertCoin, convertERC20
2. handle missing erc20 contract
3. build erc20Activity based on cosmos event (save all address as 0x)
4. save to db
```
> feat: handle cosmos convertCoin, convertErc20 in job erc20Activity

- package-lock.json
- package.json
- src/common/queue/queue-manager.ts
- src/moleculer.config.ts
> feat: pino log discord & handle throw

- src/services/evm/erc721.service.ts
- src/services/evm/erc721_media_handler.ts
- test/unit/services/erc721/erc721_handler.spec.ts
- test/unit/services/evm/erc20_handler.spec.ts
- test/unit/services/evm/erc20_reindex.spec.ts
**Normal token uri**: https://storyprotocol.mypinata.cloud/ipfs/QmNXYiP3NNLYy3CZQaArPwP141nQJBQChQ1fcd7PqxE7Ei
**New Support**:
- data:application/json;base64,eyJuYW1lIjogIlN0b3J5IFByb3RvY29sIExpY2Vuc2UgIzk5MTgiLCJkZXNjcmlwdGlvbiI6ICJMaWNlbnNlIGFncmVlbWVudCBzdGF0aW5nIHRoZSB0ZXJtcyBvZiBhIFN0b3J5IFByb3RvY29sIElQQXNzZXQiLCJleHRlcm5hbF91cmwiOiAiaHR0cHM6Ly9wcm90b2NvbC5zdG9yeXByb3RvY29sLnh5ei9pcGEvMHhiZmY2NzEyZTg5MGMyNWZjZjUxYmRjNzZjMDMwZDM5NTI4MmJlNjUzIiwiaW1hZ2UiOiAiaHR0cHM6Ly9naXRodWIuY29tL3N0b3J5cHJvdG9jb2wvcHJvdG9jb2wtY29yZS9ibG9iL21haW4vYXNzZXRzL2xpY2Vuc2UtaW1hZ2UuZ2lmIiwiYXR0cmlidXRlcyI6IFt7InRyYWl0X3R5cGUiOiAiRXhwaXJhdGlvbiIsICJ2YWx1ZSI6ICJuZXZlciJ9LHsidHJhaXRfdHlwZSI6ICJDdXJyZW5jeSIsICJ2YWx1ZSI6ICIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAifSx7InRyYWl0X3R5cGUiOiAiVVJJIiwgI …
> feat: erc721 token media special uri

- migrations/evm/20240920024049_erc20_contract_add_total_holder.ts
- src/models/account_balance.ts
- src/models/erc20_contract.ts
- src/services/evm/erc20_handler.ts
- test/unit/services/evm/erc20_handler.spec.ts
Handle erc20 total holder:
- If from balance go to 0 => total_holder --
- If to balance is zero (not found) and go to >0 => total_holder ++
> feat: erc20 total holder
